//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.31 at 01:01:59 PM BST 
//


package com.mikelus;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mikelus.jaxb.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mikelus.jaxb.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FsResponse }
     * 
     */
    public FsResponse createFsResponse() {
        return new FsResponse();
    }

    /**
     * Create an instance of {@link FsResponse.Results }
     * 
     */
    public FsResponse.Results createFsResponseResults() {
        return new FsResponse.Results();
    }

    /**
     * Create an instance of {@link FsResponse.Results.Result }
     * 
     */
    public FsResponse.Results.Result createFsResponseResultsResult() {
        return new FsResponse.Results.Result();
    }

    /**
     * Create an instance of {@link FsResponse.Results.Result.Items }
     * 
     */
    public FsResponse.Results.Result.Items createFsResponseResultsResultItems() {
        return new FsResponse.Results.Result.Items();
    }

    /**
     * Create an instance of {@link FsResponse.Results.Result.Items.Item }
     * 
     */
    public FsResponse.Results.Result.Items.Item createFsResponseResultsResultItemsItem() {
        return new FsResponse.Results.Result.Items.Item();
    }

    /**
     * Create an instance of {@link FsResponse.Results.Result.Metas }
     * 
     */
    public FsResponse.Results.Result.Metas createFsResponseResultsResultMetas() {
        return new FsResponse.Results.Result.Metas();
    }

    /**
     * Create an instance of {@link FsResponse.Results.Result.Items.Item.Value }
     * 
     */
    public FsResponse.Results.Result.Items.Item.Value createFsResponseResultsResultItemsItemValue() {
        return new FsResponse.Results.Result.Items.Item.Value();
    }

    /**
     * Create an instance of {@link FsResponse.Results.Result.Metas.Meta }
     * 
     */
    public FsResponse.Results.Result.Metas.Meta createFsResponseResultsResultMetasMeta() {
        return new FsResponse.Results.Result.Metas.Meta();
    }

}
